### PR TITLE
Grid new

### PR DESCRIPTION
**Pull request by c-johnson**
Main changes are:

- 99% complete on responsive grid classes
- Moved {vendor/flexbox-grid.scss} => {grid.scss}
- Moved {layout.scss} => {grid.scss}

Will probably move the generated classes to a separate file.

### CODE REVIEW

**Comment by galenwp** [comment]
Wanna resolve the hanging conflict in `index.html`?

**Comment by c-johnson** [comment]
Oh, right lol

**Comment by c-johnson** [comment]
Should be good.

**Comment by galenwp** [comment]
Sorry, missed that last comment somehow.

**Pull request merged**
