### PR TITLE
adding link href work sans, better legibility on grid labels

### PR DESCRIPTION
**Pull request by jyng**
1) added the link href for work sans so i could get a sense for the typography. then, changed the headings in typography section to be more descriptive. 2) small edits on grid labels to improve legibility

### CODE REVIEW

**Comment by galenwp** [comment]
This is good.  Needs a few adjustments, but I'll make them.

**Comment by galenwp** [comment]
See: https://github.com/urbit/base-css/commit/ad51b20b60bbc9d4d1f8165b015fdd8bfd4f3e64

Apparently you need to include weights when you `<link>` to Google Fonts.  I'm still a bit divided on whether or not I like the heaver weights of Work Sans.  

I'm a little confused on your "60/96 px" annotations on headings.  Is that supposed to be `font-size` / `line-height`?

**Comment by galenwp** [comment]
(Also, I pushed a big update yesterday.  Everything after the 'Type' section is basically not done.)

**Comment by jyng** [comment]
1) I like the heavier weights, but I think weights past 700(Bold) will be seldomly used.
2) Yep that's right. I see this shorthand frequently in type books, but if we want to be more explicit we could do it on a new line. Might be better for end users.
3) Just viewed it locally. It's coming together nicely. I'm wondering if we should also state the font-size and line-height for Body.

**Comment by galenwp** [comment]
1. Agree.  Although I kind of oscillate back and forth between wanting to use 900 (Black) for h1s.
2. That pattern seems fine, but I think the current values aren't right.
3. Yeah, the copy isn't done.  We should definitely note those things, I think there also needs to be some way of calling out `.class-names` throughout.  Rather than exclusively giving code samples.

**Comment by jyng** [comment]
1. Just tried playing with 800 and 900 for h1s. I can see 900 being great for headers on marketing pages, but 800 being better suited for blogpost headings. The apertures feel a bit small on 900 for written content.
work sans 800
work sans 900


2. This is my mistake. My Chrome's minimum font size was 8px and I was taking the computed values using inspect element. I'll fix them on the next PR.

**Comment by galenwp** [comment]
1. I'd be open to having some kind of 'display heading' ([a-la bootstrap](https://v4-alpha.getbootstrap.com/content/typography/#display-headings)) class that uses 900.  (and keeping the `.font-900` class.

2. No prob.  Thanks!

**Comment by galenwp** [comment]
1. I think `.h0` is too similar to the `<h>`-related classes.  Something like `.heavy` is what comes to mind — but I guess you may as well just use `.font-900`.
2. I just meant when you give an example of the usage of an element, you should also show the class name you're using, like:

# Heading one `<h1> / .h1`

or similar.

**Pull request merged**
