### PR TITLE
Styleguide updates

### PR DESCRIPTION
**Pull request by c-johnson**
Tasks include:
  - Switch from 6px to 4px- based grid 
  - Renovated type scale (roughly 1.25 scale, based on 4px instead of 6px)
  - Added set of small buttons, increased text area size, lots of other small fixin's
  - Touched up styleguide index page a bit, adding navigation, better delineated sections, etc.

Does not include:
  - Icon updates. Should do this when we get font/icon system sorted out.

### CODE REVIEW

**Comment by galenwp** [comment]
Agree that the button padding could be 'square' (width / height of padding being the same). And that the error text could be 12.

**Comment by galenwp** [comment]
I'm kind of tempted to merge this, and leave those two things as remaining issues though. I think this is reasonably complete.

**Comment by jyng** [comment]
I agree that it's reasonable complete. Let's plan on merging EOW?

**Comment by jyng** [comment]
Unrelated note: The link here is broken.
screen shot 2017-11-07 at 4 47 12 pm

**Comment by galenwp** [comment]
I wonder what I meant to link to.

**Pull request merged**
